#pragma config(Motor,  port1,           RightWheel,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LeftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LeftWheel,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task autonomous()
{
	while (1 == 1)
	{
		motor[RightWheel] = 100;
		motor[LeftWheel] = 100;
		wait1Msec(800);
		motor[RightWheel] = -100;
		motor[LeftWheel] = 100;
		wait1Msec(800);
		motor[RightWheel] = 87;
		motor[LeftWheel] = 87;
		wait1Msec(400);
		motor[RightWheel] = -100;
		motor[LeftWheel] = 100;
		wait1Msec(300);
		motor[RightWheel] = 127;
		motor[LeftWheel] = 127;
		wait1Msec(200);
	  motor[RightLift] = 76;
	  motor[LeftLift] = 76;
	  motor[RightLift] = -76;
	  motor[RightLift] = -76;


	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task usercontrol()
{

  // User control code here, inside the loop


    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

  while (1 == 1)
	{

	    motor[RightWheel]  = vexRT[Ch2];
	    motor[LeftWheel]  = vexRT[Ch3];

	    if (vexRT[Btn6U] == 1)
	  {
		  motor[RightLift]=127;
	    motor[LeftLift]=127;
	  }
	    else if (vexRT[Btn6U] == 0)

	  {
		  motor[RightLift]=0;
	    motor[LeftLift]=0;
	  }
	    if (vexRT[Btn6D] == 1)
	  {
	    motor[RightLift]= -127;
	  	motor[LeftLift]= -127;
	  }
	    else if (vexRT[Btn6D] == 0)
	  {
	  	motor[RightLift]= 0;
	  	motor[LeftLift]= 0;
	  }
	}
}
